// File generated by FlutterFire CLI & Antigravity.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AREDACTED-FIREBASE-ANDROID-KEY-00000000',
    appId: '1:1006208450463:android:7693174b80b2543b5b87aa',
    messagingSenderId: '1006208450463',
    projectId: 'guidy-19e46',
    storageBucket: 'guidy-19e46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AREDACTED-FIREBASE-APPLE-KEY-0000000000',
    appId: '1:1006208450463:ios:2ebf0c80c4ad8c6f5b87aa',
    messagingSenderId: '1006208450463',
    projectId: 'guidy-19e46',
    storageBucket: 'guidy-19e46.firebasestorage.app',
    iosClientId: '1006208450463-g64acq43s3po5ol5mu658c8ttp88ik83.apps.googleusercontent.com',
    iosBundleId: 'com.guidy.guidyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AREDACTED-FIREBASE-APPLE-KEY-0000000000',
    appId: '1:1006208450463:ios:2ebf0c80c4ad8c6f5b87aa',
    messagingSenderId: '1006208450463',
    projectId: 'guidy-19e46',
    storageBucket: 'guidy-19e46.firebasestorage.app',
    iosClientId: '1006208450463-g64acq43s3po5ol5mu658c8ttp88ik83.apps.googleusercontent.com',
    iosBundleId: 'com.guidy.guidyApp',
  );
}
