"""secrets.properties -> dart-define JSON + iOS Secrets.xcconfig.

Usage: secrets_to_defines.py <secrets.properties> <defines.json> <Secrets.xcconfig>

API_BASE_URL and ANDROID_CERT_SHA1 environment variables override the
file's values (so a Mac can point at a backend on its own IP, and a build
signed with the Mac's debug key sends that key's fingerprint). Values are never printed, only which
keys were written.
"""
import json
import os
import sys

# Keys the Dart code reads with String.fromEnvironment.
DART_KEYS = [
    "API_BASE_URL",
    "MAPS_API_KEY_ANDROID", "MAPS_API_KEY_IOS", "ANDROID_CERT_SHA1",
    "ADMOB_BANNER_AD_UNIT_ID_ANDROID", "ADMOB_BANNER_AD_UNIT_ID_IOS",
    "ADMOB_APP_OPEN_AD_UNIT_ID_ANDROID", "ADMOB_APP_OPEN_AD_UNIT_ID_IOS",
]

ENV_OVERRIDES = ["API_BASE_URL", "ANDROID_CERT_SHA1"]


def parse(path):
    out = {}
    with open(path, encoding="utf-8-sig") as f:
        for raw in f:
            line = raw.strip()
            if not line or line.startswith(("#", "!")) or "=" not in line:
                continue
            k, v = line.split("=", 1)
            k, v = k.strip(), v.strip()
            if len(v) >= 2 and v[0] == v[-1] and v[0] in "\"'":
                v = v[1:-1]
            if k:
                out[k] = v
    return out


def main(src, defines_path, xcconfig_path):
    props = parse(src)
    for k in ENV_OVERRIDES:
        if os.environ.get(k):
            props[k] = os.environ[k]
    defines = {k: props[k] for k in DART_KEYS if props.get(k)}
    with open(defines_path, "w", encoding="utf-8") as f:
        json.dump(defines, f, indent=2, sort_keys=True)
    key = props.get("MAPS_API_KEY_IOS", "")
    if any(c in key for c in "\n\r$;"):
        sys.exit("MAPS_API_KEY_IOS contains characters an xcconfig cannot hold")
    with open(xcconfig_path, "w", encoding="utf-8") as f:
        f.write("// Generated by tool/secrets_to_defines.py -- do not commit.\n")
        if key:
            f.write("MAPS_API_KEY_IOS = %s\n" % key)
    print("dart-defines: %s" % (", ".join(sorted(defines)) or "(none)"))
    print("API_BASE_URL: %s" % defines.get("API_BASE_URL", "(unset -> app's LAN fallbacks)"))
    print("MAPS_API_KEY_IOS: %s" % ("set" if key else "MISSING -- iOS map tiles will be blank"))


if __name__ == "__main__":
    if len(sys.argv) != 4:
        sys.exit(__doc__)
    main(*sys.argv[1:])
